### GENERAL SETTINGS ###

# Site settings
title: nepente
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://nepente.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: http://twitter.com/nepente_io

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Some Ave, 987,
    - 23890, New York,
    - United States.
email: hello@solidtheme.com
tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: André Poleza
    position: Desenvolvedor
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: andre.jpg
    social:
      - title: envelope # Imagem para endereço de e-mail
        url: mailto:andre@nepente.io
      - title: twitter
        url: http://twitter.com/andrepoleza
  - name: Diego Fernandez
    position: Desenvolvedor
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: diego.jpg
    social:
      - title: envelope # Imagem para endereço de e-mail
        url: mailto:diego@nepente.io
      - title: twitter
        url: http://twitter.com/diegobfernandez
  - name: Felipe Lima
    position: Desenvolvedor
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: felipe.jpg
    social:
      - title: envelope # Imagem para endereço de e-mail
        url: mailto:felipe@nepente.io
      - title: twitter
        url: http://twitter.com/limafelipe92

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
